version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - RUST_ENV=production
      - DATABASE_URL=postgres://postgres:Admin1234@db:5432/shortlink
      - BASE_URL=http://localhost:${PORT}
      - PORT=${PORT}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin1234
      POSTGRES_DB: shortlink
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
